### ISSUE TITLE
Can't play urls from a browser

### ISSUE THREAD

**Issue by sphaero** [skipmodea1/plugin.video.dumpert#5]
For example by using the chrome extension play to kodi:

logs:
```
12:02:33.268 969.822632 T:1538913200   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('title',)
                                            Traceback (most recent call last):
                                              File "/home/xbian/.kodi/addons/plugin.video.dumpert/addon.py", line 67, in <module>
                                                plugin.Main()
                                              File "/home/xbian/.kodi/addons/plugin.video.dumpert/resources/lib/dumpert_play.py", line 45, in __init__
                                                self.title = urlparse.parse_qs(urlparse.urlparse(sys.argv[2]).query)['title'][0]
                                            KeyError: ('title',)
                                            -->End of Python script error report<--
12:02:33.361 969.915283 T:1954149200   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.dumpert/?action=play&video_page_url=http%3A%2F%2Fwww.dumpert.nl%2Fmediabase%2F7095997%2F1f72985c%2Fmevrouw_heeft_internetje_thuis.html]

```

**Comment by skipmodea1** [comment]
I will have a look. Shouldn't be too hard to fix.

**Comment by skipmodea1** [comment]
Should be fixed now.
